services:
  # Django Backend API
  - type: web
    name: legalease-backend
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn legalease.wsgi:application"
    plan: free
    envVars:
      - key: DEBUG
        value: false
      - key: SECRET_KEY
        generateValue: true
      - key: GROQ_API_KEY
        sync: false  # Set this manually in Render dashboard
      - key: PYTHON_VERSION
        value: "3.11.0"

  # React Frontend (Static Site)
  - type: web
    name: legalease-frontend
    env: static
    buildCommand: cd frontend && npm ci && npm run build
    staticPublishPath: ./frontend/build
    plan: free
    routes:
      - type: rewrite
        source: /*
        destination: /index.html