# Generated by Django 4.2.7 on 2025-07-27 09:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this document', primary_key=True, serialize=False)),
                ('original_filename', models.CharField(help_text='The original name of the uploaded file', max_length=255)),
                ('file_type', models.CharField(choices=[('pdf', 'PDF Document'), ('docx', 'Word Document'), ('image', 'Image File')], help_text='Type of the uploaded file', max_length=20)),
                ('file_size', models.PositiveIntegerField(help_text='Size of the file in bytes')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When this document was uploaded')),
                ('extracted_text', models.TextField(blank=True, help_text='Text extracted from the document', null=True)),
                ('simplified_text', models.TextField(blank=True, help_text='Simplified version of the legal text', null=True)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('extracting', 'Extracting Text'), ('simplifying', 'Simplifying'), ('completed', 'Completed'), ('error', 'Error')], default='uploaded', help_text='Current processing status', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='Error message if processing failed', null=True)),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(help_text='Language code for this translation', max_length=10)),
                ('language_name', models.CharField(help_text='Human-readable language name', max_length=100)),
                ('translated_text', models.TextField(help_text='The translated version of the simplified text')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When this translation was created')),
                ('document', models.ForeignKey(help_text='The document this translation belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='documents.document')),
            ],
            options={
                'verbose_name': 'Translation',
                'verbose_name_plural': 'Translations',
                'ordering': ['-created_at'],
                'unique_together': {('document', 'language_code')},
            },
        ),
    ]
